### ISSUE TITLE
"<br/>" Tag is showing for Light Cleric Spells

### ISSUE THREAD

**Issue by JaxOffTV** [nbadal/snd-nbadal-templates#1]
![image](https://user-images.githubusercontent.com/11073599/209850724-c02e4bdd-e7f6-4285-a048-89ee91398ab2.png)

EDIT: I may be stupid and have realized that the problem would be with the source, not your template. Sorry!

EDIT2: Nevermind, does seem to be a problem with the template. I really don't know a lot about this stuff. 😅😂

**Comment by nbadal** [comment]
This should now be fixed with the changes in #2. Thanks for reporting @Dalfuss !
